### ISSUE TITLE
Simple AD not available in all regions

### ISSUE THREAD

**Issue by chchang6** [awsdocs/aws-parallelcluster-user-guide#108]
Hi, it may be worth mentioning that Simple AD is not available in us-east-2 or us-west-1, maybe just a sentence after this:

"You can use an AWS Directory Service for Microsoft Active Directory or Simple AD to manage cluster access."

For reference, see https://docs.aws.amazon.com/directoryservice/latest/admin-guide/regions.html

The instructions [here](https://docs.aws.amazon.com/directoryservice/latest/admin-guide/how_to_create_simple_ad.html) won't work, as the Simple AD option will not be available in the console.

**Comment by klstromsland** [comment]
Chris Chang, https://github.com/awsdocs/aws-parallelcluster-user-guide/commit/9d4d582e0fbcc704075eed412c8c8c4a79ceb3b8

**Comment by klstromsland** [comment]
Chris Chang, thank you for submitting this thoughtful suggestion. I've updated the documentation as follows: https://github.com/awsdocs/aws-parallelcluster-user-guide/commit/9d4d582e0fbcc704075eed412c8c8c4a79ceb3b8. Hope it helps.
