### ISSUE TITLE
Example needed: Submitting a container to the cluster 

### ISSUE THREAD

**Issue by steveisoft** [awsdocs/aws-parallelcluster-user-guide#17]
Is there a way to submit a container using awsbsub as a workload?
If so, and I assume there must be, can anyone provide an example?

**Comment by HLeeHart** [comment]
For product issues, please submit them on the AWS ParallelCluster repo at https://github.com/aws/aws-parallelcluster/issues where it will get a wider audience and allow others to learn as well.
I'm closing this issue now in favor of the issue you will file, please feel free to re-open if closed in error.
Thanks!

**Comment by HLeeHart** [comment]
For product issues, please submit them on the AWS ParallelCluster repo at https://github.com/aws/aws-parallelcluster/issues where it will get a wider audience and allow others to learn as well.
I'm closing this issue now in favor of the issue you will file, please feel free to re-open if closed in error.
Thanks!
