### ISSUE TITLE
Are the ParallelClusterUserPolicy examples missing ec2:CreateRoute?

### ISSUE THREAD

**Issue by alanbchristie** [awsdocs/aws-parallelcluster-user-guide#44]
We're trying to avoid using a user with **AdministratorAccess** permissions and instead are using
a dedicated user with the example **ParallelClusterUserPolicy using SGE, Slurm, or Torque** policy attached.

When running the `pcluster configure` command, if you're also creating VPC, you are presented with the following error:

```
  - AWS::EC2::NatGateway NatGatewayPublic Resource creation cancelled
  - AWS::EC2::Route DefaultRouteDependsOnPublic API: ec2:CreateRoute You are not authorized to perform this operation. Encoded authorization failure message: zAGBhfi0xy0DfdSlZda7EISDUQLDgYLXA7wYVA3BeJmyh_v0xx_MNOCXKQxx6DYW_rtO6dGQPqwOClyZDBUOihiCPqNF6MFDbTDF9_USSFI-whQztOIq4KFlf5QDAkc7mFxtPcvXYO-3ysosH_dl9qfCp7MzWzOAEwSnpapbGCqkaqdy136igj0hLa95rudFbbVw_vMn8HS4Bcko3mIbtrUPuNn5aeqB_fqO9ZgE_-KLPnW-xh1sEgZdMC_YTBzw45C4smDwzdlJ4BY5ZNj3w1c2JjfGsA5HoBJoVxGWnCDlr4w2Kmb3he1HAgtTuXENI-OgWygV4R7jdR4sF8lz5PZQNTlQ6ndSgptt1SrENbQNu0GU3jXDP8x9utw78k3LRDpXA1eHCf7lDG6kZ5LlmfWCkV2dbc3WzAFT14CVn3k2ReStozyAO9IaqXHqng_eXPlrNGbjoyRDiEfiuN28LHxz7Qw3bbg_qpMCKiv4b8K3X25Z0IGAISqkGL94pDDCrskqfcyv8wNVIBhDufXuV1uO_nbn-YVpVPS4qrJfl3v9haB-y9cmfBDprGWQxlKrBnpWuZy1CDHBXy9KeardRPPQY-B1XGHQvpPEcLJYVYnSG-Q7vFwq7PVsfpibcLnNXIq97EQ1ebSNhPKRHN5044qLvFgrJOZf2oahUi42yFUP586Ne4_YySM1H2A2FVs7JExnXApw5XuDbq3gf_AIPnMMuSLsHQ6-_B7NkeC5eMbRNQnRabDIYgXT9u7q47ew7X4Woec_LFVyPIqiWtjQtF9k2UbVLroOxVu8phPYuDyyZPaT2IX-nSdY-csVqA5j94FqgNh-
```

We can fix this by adding `ec2:CreateRoute` to the user's permissions.

Are the **ParallelClusterUserPolicy** examples (in `iam.md`) - one for "using awsbatch" and one for "using SGE, Slurm or Torque" - missing the `ec2:CreateRoute` action in the `NetworkingEasyConfig` Sid? I only ask because `NetworkingEasyConfig` seems to have everything else related to networking except `CreateRoute`.

**Comment by HLeeHart** [comment]
Thank you for raising this issue. I have updated the docs with this commit:
https://github.com/awsdocs/aws-parallelcluster-user-guide/commit/2adfb2171bac7cfb1caf1f47aaf13106224d11dc
